---
title: "DataCleaning"
author: "Gerardo Gutierrez"
date: "2025-11-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load necessary libraries
library(dplyr) # data wrangling
library(tidyr) # data tidying and reshaping
library(ggplot2) # pretty plots
library(readr)
# Load the dataset
data <- read_csv("../data/raw_data.csv")
```

```{r}
# Inspect the dataset
View(data)
head(data)


```

```{r}
summary(data)
```

```{r}
str(data)

```

```{r}
# Check for missing values
colSums(is.na(data))

```

```{r}
# get unique values for categorical variables
sapply(data, function(x) if(is.factor(x) || is.character(x)) unique(x))

```
```{r}
# list column names 
colnames(data)
```

```{r}
# build regresssion model with all variables  with paddy yield as target
paddy_yield <- data$'Paddy yield(in Kg)'
model <- lm(`Paddy yield(in Kg)` ~ . , data = data)
summary(model)

```
```{r}
paddy_yield
```

```{r}
# check data types
sapply(data, class)
```

